# Get editor completions based on the config schema
#"$schema" = "https://starship.rs/config-schema.json"

# Inserts a blank line between shell prompts
add_newline = true

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10

# Replace the "?" symbol in the prompt with "?"
[character] # The name of the module we are configuring is "character"
success_symbol = "[->](bold green)" # The "success_symbol" segment is being set to "?" with the color "bold green"

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[directory]
truncation_length = 10
truncate_to_repo = false
style = "green"
format = "[$path]($style)[$lock_symbol]($lock_style) "

[git_branch]
symbol = ""
style = "bold white"
format = '[\($symbol$branch\)]($style) '

[git_status]
# I don't care about untracked files or that there's a stash present.
untracked = ""
format = '([\[$conflicted$deleted$renamed$modified$staged$behind\]]($style) )'
modified = '*'

[status]
disabled = false
format = '[\[$status - $common_meaning\]](green)'
